version: "3.8"

services:
  web:
    image: php:apache
    volumes:
      - "./app:/var/www/html"
    ports:
      - "80:80"
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 50M
      restart_policy:
        condition: on-failure

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 50M
      restart_policy:
        condition: on-failure

volumes:
  db_data:
